version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:e0d2927fd6d7cbf4d0a79854123d12f07bc1091c
    ports:
      - "5000:5000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml