// @generated by protobuf-ts 2.8.2 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "proto/api.proto" (package "api", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message api.ApiOwner
 */
export interface ApiOwner {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
}
/**
 * @generated from protobuf message api.ApiRestaurant
 */
export interface ApiRestaurant {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: bytes logo = 4;
     */
    logo: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiItem
 */
export interface ApiItem {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: float price = 3;
     */
    price: number;
    /**
     * @generated from protobuf field: string description = 4;
     */
    description: string;
    /**
     * @generated from protobuf field: string category = 5;
     */
    category: string;
    /**
     * @generated from protobuf field: bytes image = 6;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiOrder
 */
export interface ApiOrder {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string itemName = 2;
     */
    itemName: string;
    /**
     * @generated from protobuf field: float requested_at = 3;
     */
    requestedAt: number;
    /**
     * @generated from protobuf field: bool completed = 4;
     */
    completed: boolean;
    /**
     * @generated from protobuf field: int32 tableNumber = 5;
     */
    tableNumber: number;
    /**
     * @generated from protobuf field: string description = 6;
     */
    description: string;
}
/**
 * @generated from protobuf message api.ApiSignUpRequest
 */
export interface ApiSignUpRequest {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
}
/**
 * @generated from protobuf message api.ApiSignUpResponse
 */
export interface ApiSignUpResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiSignInRequest
 */
export interface ApiSignInRequest {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
}
/**
 * @generated from protobuf message api.ApiSignInResponse
 */
export interface ApiSignInResponse {
    /**
     * @generated from protobuf field: api.ApiOwner owner = 1;
     */
    owner?: ApiOwner;
    /**
     * @generated from protobuf field: string jwt = 2;
     */
    jwt: string;
}
/**
 * @generated from protobuf message api.ApiCreateRestaurantRequest
 */
export interface ApiCreateRestaurantRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: bytes image = 4;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiCreateRestaurantResponse
 */
export interface ApiCreateRestaurantResponse {
    /**
     * @generated from protobuf field: string restId = 1;
     */
    restId: string;
}
/**
 * @generated from protobuf message api.ApiDeleteRestaurantRequest
 */
export interface ApiDeleteRestaurantRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string restId = 2;
     */
    restId: string;
}
/**
 * @generated from protobuf message api.ApiDeleteRestaurantResponse
 */
export interface ApiDeleteRestaurantResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiUpdateRestaurantRequest
 */
export interface ApiUpdateRestaurantRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string restId = 2;
     */
    restId: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 4;
     */
    description: string;
    /**
     * @generated from protobuf field: bytes image = 5;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiUpdateRestaurantResponse
 */
export interface ApiUpdateRestaurantResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiGetRestaurantRequest
 */
export interface ApiGetRestaurantRequest {
    /**
     * @generated from protobuf field: string restId = 1;
     */
    restId: string;
}
/**
 * @generated from protobuf message api.ApiGetRestaurantResponse
 */
export interface ApiGetRestaurantResponse {
    /**
     * @generated from protobuf field: api.ApiRestaurant restaurant = 1;
     */
    restaurant?: ApiRestaurant;
}
/**
 * @generated from protobuf message api.ApiGetRestaurantsRequest
 */
export interface ApiGetRestaurantsRequest {
    /**
     * @generated from protobuf field: string ownerId = 1;
     */
    ownerId: string;
}
/**
 * @generated from protobuf message api.ApiGetRestaurantsResponse
 */
export interface ApiGetRestaurantsResponse {
    /**
     * @generated from protobuf field: repeated api.ApiRestaurant restaurants = 1;
     */
    restaurants: ApiRestaurant[];
}
/**
 * @generated from protobuf message api.ApiAddItemRequest
 */
export interface ApiAddItemRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string restId = 2;
     */
    restId: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: float price = 4;
     */
    price: number;
    /**
     * @generated from protobuf field: string description = 5;
     */
    description: string;
    /**
     * @generated from protobuf field: string category = 6;
     */
    category: string;
    /**
     * @generated from protobuf field: bytes image = 7;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiAddItemResponse
 */
export interface ApiAddItemResponse {
    /**
     * @generated from protobuf field: string itemId = 1;
     */
    itemId: string;
}
/**
 * @generated from protobuf message api.ApiRemoveItemRequest
 */
export interface ApiRemoveItemRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string itemId = 2;
     */
    itemId: string;
}
/**
 * @generated from protobuf message api.ApiRemoveItemResponse
 */
export interface ApiRemoveItemResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiUpdateItemRequest
 */
export interface ApiUpdateItemRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string itemId = 2;
     */
    itemId: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: float price = 4;
     */
    price: number;
    /**
     * @generated from protobuf field: string description = 5;
     */
    description: string;
    /**
     * @generated from protobuf field: string category = 6;
     */
    category: string;
    /**
     * @generated from protobuf field: bytes image = 7;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message api.ApiUpdateItemResponse
 */
export interface ApiUpdateItemResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiGetItemRequest
 */
export interface ApiGetItemRequest {
    /**
     * @generated from protobuf field: string itemId = 1;
     */
    itemId: string;
}
/**
 * @generated from protobuf message api.ApiGetItemResponse
 */
export interface ApiGetItemResponse {
    /**
     * @generated from protobuf field: api.ApiItem item = 1;
     */
    item?: ApiItem;
}
/**
 * @generated from protobuf message api.ApiGetItemsRequest
 */
export interface ApiGetItemsRequest {
    /**
     * @generated from protobuf field: string restId = 1;
     */
    restId: string;
    /**
     * @generated from protobuf field: string category = 2;
     */
    category: string;
}
/**
 * @generated from protobuf message api.ApiGetItemsResponse
 */
export interface ApiGetItemsResponse {
    /**
     * @generated from protobuf field: repeated api.ApiItem items = 1;
     */
    items: ApiItem[];
}
/**
 * @generated from protobuf message api.ApiMakeOrderRequest
 */
export interface ApiMakeOrderRequest {
    /**
     * @generated from protobuf field: string itemId = 1;
     */
    itemId: string;
    /**
     * @generated from protobuf field: int32 tableNumber = 2;
     */
    tableNumber: number;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
}
/**
 * @generated from protobuf message api.ApiMakeOrderResponse
 */
export interface ApiMakeOrderResponse {
    /**
     * @generated from protobuf field: string orderId = 1;
     */
    orderId: string;
}
/**
 * @generated from protobuf message api.ApiCompleteOrderRequest
 */
export interface ApiCompleteOrderRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string orderId = 2;
     */
    orderId: string;
}
/**
 * @generated from protobuf message api.ApiCompleteOrderResponse
 */
export interface ApiCompleteOrderResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
}
/**
 * @generated from protobuf message api.ApiGetOrdersRequest
 */
export interface ApiGetOrdersRequest {
    /**
     * @generated from protobuf field: string jwt = 1;
     */
    jwt: string;
    /**
     * @generated from protobuf field: string restId = 2;
     */
    restId: string;
    /**
     * @generated from protobuf field: float since = 3;
     */
    since: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ApiOwner$Type extends MessageType<ApiOwner> {
    constructor() {
        super("api.ApiOwner", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiOwner
 */
export const ApiOwner = new ApiOwner$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiRestaurant$Type extends MessageType<ApiRestaurant> {
    constructor() {
        super("api.ApiRestaurant", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "logo", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiRestaurant
 */
export const ApiRestaurant = new ApiRestaurant$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiItem$Type extends MessageType<ApiItem> {
    constructor() {
        super("api.ApiItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiItem
 */
export const ApiItem = new ApiItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiOrder$Type extends MessageType<ApiOrder> {
    constructor() {
        super("api.ApiOrder", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "itemName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "requested_at", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "completed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "tableNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiOrder
 */
export const ApiOrder = new ApiOrder$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiSignUpRequest$Type extends MessageType<ApiSignUpRequest> {
    constructor() {
        super("api.ApiSignUpRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiSignUpRequest
 */
export const ApiSignUpRequest = new ApiSignUpRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiSignUpResponse$Type extends MessageType<ApiSignUpResponse> {
    constructor() {
        super("api.ApiSignUpResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiSignUpResponse
 */
export const ApiSignUpResponse = new ApiSignUpResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiSignInRequest$Type extends MessageType<ApiSignInRequest> {
    constructor() {
        super("api.ApiSignInRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiSignInRequest
 */
export const ApiSignInRequest = new ApiSignInRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiSignInResponse$Type extends MessageType<ApiSignInResponse> {
    constructor() {
        super("api.ApiSignInResponse", [
            { no: 1, name: "owner", kind: "message", T: () => ApiOwner },
            { no: 2, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiSignInResponse
 */
export const ApiSignInResponse = new ApiSignInResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiCreateRestaurantRequest$Type extends MessageType<ApiCreateRestaurantRequest> {
    constructor() {
        super("api.ApiCreateRestaurantRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiCreateRestaurantRequest
 */
export const ApiCreateRestaurantRequest = new ApiCreateRestaurantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiCreateRestaurantResponse$Type extends MessageType<ApiCreateRestaurantResponse> {
    constructor() {
        super("api.ApiCreateRestaurantResponse", [
            { no: 1, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiCreateRestaurantResponse
 */
export const ApiCreateRestaurantResponse = new ApiCreateRestaurantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiDeleteRestaurantRequest$Type extends MessageType<ApiDeleteRestaurantRequest> {
    constructor() {
        super("api.ApiDeleteRestaurantRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiDeleteRestaurantRequest
 */
export const ApiDeleteRestaurantRequest = new ApiDeleteRestaurantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiDeleteRestaurantResponse$Type extends MessageType<ApiDeleteRestaurantResponse> {
    constructor() {
        super("api.ApiDeleteRestaurantResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiDeleteRestaurantResponse
 */
export const ApiDeleteRestaurantResponse = new ApiDeleteRestaurantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiUpdateRestaurantRequest$Type extends MessageType<ApiUpdateRestaurantRequest> {
    constructor() {
        super("api.ApiUpdateRestaurantRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiUpdateRestaurantRequest
 */
export const ApiUpdateRestaurantRequest = new ApiUpdateRestaurantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiUpdateRestaurantResponse$Type extends MessageType<ApiUpdateRestaurantResponse> {
    constructor() {
        super("api.ApiUpdateRestaurantResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiUpdateRestaurantResponse
 */
export const ApiUpdateRestaurantResponse = new ApiUpdateRestaurantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetRestaurantRequest$Type extends MessageType<ApiGetRestaurantRequest> {
    constructor() {
        super("api.ApiGetRestaurantRequest", [
            { no: 1, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetRestaurantRequest
 */
export const ApiGetRestaurantRequest = new ApiGetRestaurantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetRestaurantResponse$Type extends MessageType<ApiGetRestaurantResponse> {
    constructor() {
        super("api.ApiGetRestaurantResponse", [
            { no: 1, name: "restaurant", kind: "message", T: () => ApiRestaurant }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetRestaurantResponse
 */
export const ApiGetRestaurantResponse = new ApiGetRestaurantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetRestaurantsRequest$Type extends MessageType<ApiGetRestaurantsRequest> {
    constructor() {
        super("api.ApiGetRestaurantsRequest", [
            { no: 1, name: "ownerId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetRestaurantsRequest
 */
export const ApiGetRestaurantsRequest = new ApiGetRestaurantsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetRestaurantsResponse$Type extends MessageType<ApiGetRestaurantsResponse> {
    constructor() {
        super("api.ApiGetRestaurantsResponse", [
            { no: 1, name: "restaurants", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ApiRestaurant }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetRestaurantsResponse
 */
export const ApiGetRestaurantsResponse = new ApiGetRestaurantsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiAddItemRequest$Type extends MessageType<ApiAddItemRequest> {
    constructor() {
        super("api.ApiAddItemRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiAddItemRequest
 */
export const ApiAddItemRequest = new ApiAddItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiAddItemResponse$Type extends MessageType<ApiAddItemResponse> {
    constructor() {
        super("api.ApiAddItemResponse", [
            { no: 1, name: "itemId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiAddItemResponse
 */
export const ApiAddItemResponse = new ApiAddItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiRemoveItemRequest$Type extends MessageType<ApiRemoveItemRequest> {
    constructor() {
        super("api.ApiRemoveItemRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "itemId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiRemoveItemRequest
 */
export const ApiRemoveItemRequest = new ApiRemoveItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiRemoveItemResponse$Type extends MessageType<ApiRemoveItemResponse> {
    constructor() {
        super("api.ApiRemoveItemResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiRemoveItemResponse
 */
export const ApiRemoveItemResponse = new ApiRemoveItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiUpdateItemRequest$Type extends MessageType<ApiUpdateItemRequest> {
    constructor() {
        super("api.ApiUpdateItemRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "itemId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiUpdateItemRequest
 */
export const ApiUpdateItemRequest = new ApiUpdateItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiUpdateItemResponse$Type extends MessageType<ApiUpdateItemResponse> {
    constructor() {
        super("api.ApiUpdateItemResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiUpdateItemResponse
 */
export const ApiUpdateItemResponse = new ApiUpdateItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetItemRequest$Type extends MessageType<ApiGetItemRequest> {
    constructor() {
        super("api.ApiGetItemRequest", [
            { no: 1, name: "itemId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetItemRequest
 */
export const ApiGetItemRequest = new ApiGetItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetItemResponse$Type extends MessageType<ApiGetItemResponse> {
    constructor() {
        super("api.ApiGetItemResponse", [
            { no: 1, name: "item", kind: "message", T: () => ApiItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetItemResponse
 */
export const ApiGetItemResponse = new ApiGetItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetItemsRequest$Type extends MessageType<ApiGetItemsRequest> {
    constructor() {
        super("api.ApiGetItemsRequest", [
            { no: 1, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetItemsRequest
 */
export const ApiGetItemsRequest = new ApiGetItemsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetItemsResponse$Type extends MessageType<ApiGetItemsResponse> {
    constructor() {
        super("api.ApiGetItemsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ApiItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetItemsResponse
 */
export const ApiGetItemsResponse = new ApiGetItemsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiMakeOrderRequest$Type extends MessageType<ApiMakeOrderRequest> {
    constructor() {
        super("api.ApiMakeOrderRequest", [
            { no: 1, name: "itemId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tableNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiMakeOrderRequest
 */
export const ApiMakeOrderRequest = new ApiMakeOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiMakeOrderResponse$Type extends MessageType<ApiMakeOrderResponse> {
    constructor() {
        super("api.ApiMakeOrderResponse", [
            { no: 1, name: "orderId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiMakeOrderResponse
 */
export const ApiMakeOrderResponse = new ApiMakeOrderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiCompleteOrderRequest$Type extends MessageType<ApiCompleteOrderRequest> {
    constructor() {
        super("api.ApiCompleteOrderRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "orderId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiCompleteOrderRequest
 */
export const ApiCompleteOrderRequest = new ApiCompleteOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiCompleteOrderResponse$Type extends MessageType<ApiCompleteOrderResponse> {
    constructor() {
        super("api.ApiCompleteOrderResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiCompleteOrderResponse
 */
export const ApiCompleteOrderResponse = new ApiCompleteOrderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApiGetOrdersRequest$Type extends MessageType<ApiGetOrdersRequest> {
    constructor() {
        super("api.ApiGetOrdersRequest", [
            { no: 1, name: "jwt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "restId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "since", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message api.ApiGetOrdersRequest
 */
export const ApiGetOrdersRequest = new ApiGetOrdersRequest$Type();
/**
 * @generated ServiceType for protobuf service api.Api
 */
export const Api = new ServiceType("api.Api", [
    { name: "signUp", options: {}, I: ApiSignUpRequest, O: ApiSignUpResponse },
    { name: "signIn", options: {}, I: ApiSignInRequest, O: ApiSignInResponse },
    { name: "createRestaurant", options: {}, I: ApiCreateRestaurantRequest, O: ApiCreateRestaurantResponse },
    { name: "deleteRestaurant", options: {}, I: ApiDeleteRestaurantRequest, O: ApiDeleteRestaurantResponse },
    { name: "updateRestaurant", options: {}, I: ApiUpdateRestaurantRequest, O: ApiUpdateRestaurantResponse },
    { name: "getRestaurant", options: {}, I: ApiGetRestaurantRequest, O: ApiGetRestaurantResponse },
    { name: "getRestaurants", options: {}, I: ApiGetRestaurantsRequest, O: ApiGetRestaurantsResponse },
    { name: "addItem", options: {}, I: ApiAddItemRequest, O: ApiAddItemResponse },
    { name: "removeItem", options: {}, I: ApiRemoveItemRequest, O: ApiRemoveItemResponse },
    { name: "updateItem", options: {}, I: ApiUpdateItemRequest, O: ApiUpdateItemResponse },
    { name: "getItem", options: {}, I: ApiGetItemRequest, O: ApiGetItemResponse },
    { name: "getItems", options: {}, I: ApiGetItemsRequest, O: ApiGetItemsResponse },
    { name: "makeOrder", options: {}, I: ApiMakeOrderRequest, O: ApiMakeOrderResponse },
    { name: "completeOrder", options: {}, I: ApiCompleteOrderRequest, O: ApiCompleteOrderResponse },
    { name: "getOrders", serverStreaming: true, options: {}, I: ApiGetOrdersRequest, O: ApiOrder }
]);
