version: "3.8"
services:
  envoy:
    image: envoyproxy/envoy:v1.19-latest
    container_name: envoy
    ports:
      - "5000:5000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml